package io.jenkins.plugins.codeInsights.domain

import spock.lang.Specification

import java.nio.file.Path

class QodanaAnnotationProviderTest extends Specification {

    def 'convert returns annotations'() {
        given:
        final def content = Path.of('src', 'test', 'resources', 'qodana-report.json').getText('UTF-8')
        final def sut = new QodanaAnnotationProvider(content)

        expect:
        sut.convert() == [
            new Annotation(513, "Call to 'toArray()' with pre-sized array argument 'new Class[rawExtraInterfaces.size()]'", "src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java", Severity.MEDIUM, null),
            new Annotation(280, "Call to 'toArray()' with pre-sized array argument 'new Class[targets.size()]'", "src/main/java/org/mockito/internal/creation/bytebuddy/InlineBytecodeGenerator.java", Severity.MEDIUM, null),
            new Annotation(83, "Call to 'toArray()' with pre-sized array argument 'new File[results.size()]'", "subprojects/android/src/main/java/org/mockito/android/internal/creation/AndroidTempFileLocator.java", Severity.MEDIUM, null),
            new Annotation(147, "Redundant call to 'isInstance()'", "src/main/java/org/mockito/internal/MockitoCore.java", Severity.MEDIUM, null),
            new Annotation(154, "Redundant call to 'cast()'", "src/main/java/org/mockito/internal/MockitoCore.java", Severity.MEDIUM, null),
            new Annotation(125, "Redundant call to 'isInstance()'", "src/main/java/org/mockito/internal/MockitoCore.java", Severity.MEDIUM, null),
            new Annotation(132, "Redundant call to 'cast()'", "src/main/java/org/mockito/internal/MockitoCore.java", Severity.MEDIUM, null),
            new Annotation(727, "Casting 'o' to 'TypeVarBoundedType' will produce 'ClassCastException' for any non-null value", "src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java", Severity.MEDIUM, null),
            new Annotation(399, "Method invocation 'asErasure' may produce 'NullPointerException'", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(42, "Method invocation 'answer' may produce 'NullPointerException'", "src/main/java/org/mockito/internal/stubbing/StubbedInvocationMatcher.java", Severity.MEDIUM, null),
            new Annotation(739, "Parameter can be converted to a local variable", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(113, "Parameter can be converted to a local variable", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(710, "Parameter can be converted to a local variable", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(688, "Parameter can be converted to a local variable", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(130, "Deprecated member 'isLenient' is still used", "src/main/java/org/mockito/mock/MockCreationSettings.java", Severity.MEDIUM, null),
            new Annotation(22, "Deprecated member 'VarargMatcher' is still used", "src/main/java/org/mockito/internal/matchers/VarargMatcher.java", Severity.MEDIUM, null),
            new Annotation(25, "Cannot resolve method 'getInstance' with specified argument types", "src/main/java/org/mockito/internal/creation/bytebuddy/StackWalkerChecker.java", Severity.MEDIUM, null),
            new Annotation(26, "Obsolete collection type 'Stack' used", "src/main/java/org/mockito/internal/progress/ArgumentMatcherStorageImpl.java", Severity.MEDIUM, null),
            new Annotation(26, "Obsolete collection type 'Stack<>' used", "src/main/java/org/mockito/internal/progress/ArgumentMatcherStorageImpl.java", Severity.MEDIUM, null),
            new Annotation(40, "Non-serializable field 'args' in a Serializable class", "src/main/java/org/mockito/internal/creation/proxy/InvokeDefaultProxy.java", Severity.MEDIUM, null),
            new Annotation(38, "Non-serializable field 'proxy' in a Serializable class", "src/main/java/org/mockito/internal/creation/proxy/InvokeDefaultProxy.java", Severity.MEDIUM, null),
            new Annotation(80, "Non-serializable field 'args' in a Serializable class", "src/main/java/org/mockito/internal/creation/proxy/MethodHandleProxy.java", Severity.MEDIUM, null),
            new Annotation(46, "Non-serializable field 'outerClassInstance' in a Serializable class", "src/main/java/org/mockito/internal/creation/settings/CreationSettings.java", Severity.MEDIUM, null),
            new Annotation(30, "Non-serializable field 'spiedInstance' in a Serializable class", "src/main/java/org/mockito/internal/creation/settings/CreationSettings.java", Severity.MEDIUM, null),
            new Annotation(47, "Non-serializable field 'constructorArgs' in a Serializable class", "src/main/java/org/mockito/internal/creation/settings/CreationSettings.java", Severity.MEDIUM, null),
            new Annotation(47, "Non-serializable field 'constructorArgs' in a Serializable class", "src/main/java/org/mockito/internal/creation/MockSettingsImpl.java", Severity.MEDIUM, null),
            new Annotation(46, "Non-serializable field 'outerClassInstance' in a Serializable class", "src/main/java/org/mockito/internal/creation/MockSettingsImpl.java", Severity.MEDIUM, null),
            new Annotation(14, "Non-serializable field 'wanted' in a Serializable class", "src/main/java/org/mockito/internal/matchers/Same.java", Severity.MEDIUM, null),
            new Annotation(14, "Non-serializable field 'wanted' in a Serializable class", "src/main/java/org/mockito/internal/matchers/Equals.java", Severity.MEDIUM, null),
            new Annotation(13, "Non-serializable field 'wanted' in a Serializable class", "src/main/java/org/mockito/internal/matchers/apachecommons/ReflectionEquals.java", Severity.MEDIUM, null),
            new Annotation(286, "Non-serializable field 'origin' in a Serializable class", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(210, "Non-serializable field 'selfCallInfo' in a Serializable class", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(216, "Non-serializable field 'arguments' in a Serializable class", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(282, "Non-serializable field 'selfCallInfo' in a Serializable class", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(212, "Non-serializable field 'origin' in a Serializable class", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(288, "Non-serializable field 'arguments' in a Serializable class", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(246, "Non-serializable field 'arguments' in a Serializable class", "src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java", Severity.MEDIUM, null),
            new Annotation(25, "Non-serializable field 'usedAtLock' in a Serializable class", "src/main/java/org/mockito/internal/stubbing/StubbedInvocationMatcher.java", Severity.MEDIUM, null),
            new Annotation(20, "Non-serializable field 'value' in a Serializable class", "src/main/java/org/mockito/internal/stubbing/answers/Returns.java", Severity.MEDIUM, null),
            new Annotation(27, "Non-serializable field 'delegatedObject' in a Serializable class", "src/main/java/org/mockito/internal/stubbing/defaultanswers/ForwardsInvocations.java", Severity.MEDIUM, null),
            new Annotation(29, "Non-serializable field 'rawArguments' in a Serializable class", "src/main/java/org/mockito/internal/invocation/InterceptedInvocation.java", Severity.MEDIUM, null),
            new Annotation(28, "Non-serializable field 'arguments' in a Serializable class", "src/main/java/org/mockito/internal/invocation/InterceptedInvocation.java", Severity.MEDIUM, null),
            new Annotation(29, "Empty 'catch' block", "src/main/java/org/mockito/internal/junit/ExceptionFactory.java", Severity.MEDIUM, null),
            new Annotation(26, "Class member declared 'protected' in 'final' class", "src/main/java/org/mockito/internal/MockedConstructionImpl.java", Severity.MEDIUM, null),
            new Annotation(40, "Class member declared 'protected' in 'final' class", "src/main/java/org/mockito/internal/MockedStaticImpl.java", Severity.MEDIUM, null),
            new Annotation(102, "'StringBuilder' can be replaced with 'String'", "src/main/java/org/mockito/internal/util/reflection/BeanPropertySetter.java", Severity.MEDIUM, null),
            new Annotation(372, "Call to default 'toString()' on 'target'", "src/main/java/org/mockito/internal/util/reflection/InstrumentationMemberAccessor.java", Severity.MEDIUM, null),
            new Annotation(378, "Call to default 'toString()' on 'target'", "src/main/java/org/mockito/internal/util/reflection/InstrumentationMemberAccessor.java", Severity.MEDIUM, null),
            new Annotation(393, "Call to default 'toString()' on 'target'", "src/main/java/org/mockito/internal/util/reflection/InstrumentationMemberAccessor.java", Severity.MEDIUM, null),
            new Annotation(406, "Call to default 'toString()' on 'target'", "src/main/java/org/mockito/internal/util/reflection/InstrumentationMemberAccessor.java", Severity.MEDIUM, null),
            new Annotation(148, "Call to default 'toString()' on 'verificationMode'", "src/main/java/org/mockito/internal/progress/MockingProgressImpl.java", Severity.MEDIUM, null),
            new Annotation(52, "Empty string used in concatenation", "src/main/java/org/mockito/internal/junit/StubbingArgMismatches.java", Severity.MEDIUM, null),
            new Annotation(105, "'ConcurrentMap, V>' may not contain keys of type 'LatentKey'", "src/main/java/org/mockito/internal/util/concurrent/WeakConcurrentMap.java", Severity.MEDIUM, null),
            new Annotation(81, "'ConcurrentMap, V>' may not contain keys of type 'LatentKey'", "src/main/java/org/mockito/internal/util/concurrent/WeakConcurrentMap.java", Severity.MEDIUM, null),
            new Annotation(59, "'ConcurrentMap, V>' may not contain keys of type 'LatentKey'", "src/main/java/org/mockito/internal/util/concurrent/WeakConcurrentMap.java", Severity.MEDIUM, null),
            new Annotation(13, "Abstract class 'Platform' has no concrete subclass", "src/main/java/org/mockito/internal/util/Platform.java", Severity.MEDIUM, null),
            new Annotation(12, "Abstract class 'Sets' has no concrete subclass", "src/main/java/org/mockito/internal/util/collections/Sets.java", Severity.MEDIUM, null),
            new Annotation(11, "Abstract class 'DefaultAnswerValidator' has no concrete subclass", "src/main/java/org/mockito/internal/stubbing/answers/DefaultAnswerValidator.java", Severity.MEDIUM, null),
            new Annotation(727, "No class found which is a subtype of both 'WildcardType' and 'TypeVariable'", "src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java", Severity.MEDIUM, null),
            new Annotation(126, "Result of 'Checks.checkNotNull()' is ignored", "src/main/java/org/mockito/internal/creation/MockSettingsImpl.java", Severity.MEDIUM, null),
            new Annotation(166, "Can be replaced with 'isEmpty()'", "subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java", Severity.MEDIUM, null),
            new Annotation(171, "Can be replaced with 'isEmpty()'", "subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java", Severity.MEDIUM, null),
            new Annotation(155, "'while' statement cannot complete without throwing an exception", "src/main/java/org/mockito/internal/util/concurrent/WeakConcurrentMap.java", Severity.MEDIUM, null),
            new Annotation(36, "Field 'invocationForStubbing' is accessed in both synchronized and unsynchronized contexts", "src/main/java/org/mockito/internal/stubbing/InvocationContainerImpl.java", Severity.MEDIUM, null),
            new Annotation(207, "Call to 'set.removeAll(list)' may work slowly", "src/main/java/org/mockito/internal/progress/MockingProgressImpl.java", Severity.MEDIUM, null),
            new Annotation(581, "Array objects are compared using '==', not 'Arrays.equals()'", "src/main/java/org/mockito/internal/matchers/apachecommons/EqualsBuilder.java", Severity.MEDIUM, null),
            new Annotation(550, "Array objects are compared using '==', not 'Arrays.equals()'", "src/main/java/org/mockito/internal/matchers/apachecommons/EqualsBuilder.java", Severity.MEDIUM, null),
            new Annotation(705, "Array objects are compared using '==', not 'Arrays.equals()'", "src/main/java/org/mockito/internal/matchers/apachecommons/EqualsBuilder.java", Severity.MEDIUM, null),
            new Annotation(643, "Array objects are compared using '==', not 'Arrays.equals()'", "src/main/java/org/mockito/internal/matchers/apachecommons/EqualsBuilder.java", Severity.MEDIUM, null),
            new Annotation(674, "Array objects are compared using '==', not 'Arrays.equals()'", "src/main/java/org/mockito/internal/matchers/apachecommons/EqualsBuilder.java", Severity.MEDIUM, null),
            new Annotation(612, "Array objects are compared using '==', not 'Arrays.equals()'", "src/main/java/org/mockito/internal/matchers/apachecommons/EqualsBuilder.java", Severity.MEDIUM, null),
            new Annotation(767, "Array objects are compared using '==', not 'Arrays.equals()'", "src/main/java/org/mockito/internal/matchers/apachecommons/EqualsBuilder.java", Severity.MEDIUM, null),
            new Annotation(519, "Array objects are compared using '==', not 'Arrays.equals()'", "src/main/java/org/mockito/internal/matchers/apachecommons/EqualsBuilder.java", Severity.MEDIUM, null),
            new Annotation(736, "Array objects are compared using '==', not 'Arrays.equals()'", "src/main/java/org/mockito/internal/matchers/apachecommons/EqualsBuilder.java", Severity.MEDIUM, null),
            new Annotation(132, "Lock operations on 'this' may have unforeseen side-effects", "src/main/java/org/mockito/internal/creation/bytebuddy/ModuleHandler.java", Severity.MEDIUM, null),
            new Annotation(216, "Lock operations on 'this' may have unforeseen side-effects", "src/main/java/org/mockito/internal/creation/bytebuddy/InlineBytecodeGenerator.java", Severity.MEDIUM, null),
            new Annotation(80, "Lock operations on 'this' may have unforeseen side-effects", "src/main/java/org/mockito/internal/debugging/LocationImpl.java", Severity.MEDIUM, null),
            new Annotation(91, "Lock operations on 'this' may have unforeseen side-effects", "src/main/java/org/mockito/internal/debugging/Java9PlusLocationImpl.java", Severity.MEDIUM, null),
            new Annotation(88, "Call to 'asList()' with only one argument", "src/main/java/org/mockito/internal/verification/checkers/NumberOfInvocationsChecker.java", Severity.MEDIUM, null),
            new Annotation(131, "'injectionOccurred |= true' can be simplified to 'injectionOccurred=true'", "src/main/java/org/mockito/internal/configuration/injection/PropertyAndSetterInjection.java", Severity.MEDIUM, null),
            new Annotation(44, "Call to 'start()' during object construction", "src/main/java/org/mockito/internal/util/concurrent/WeakConcurrentMap.java", Severity.MEDIUM, null),
            new Annotation(37, "Variable 'matchersBinder' initializer 'new MatchersBinder()' is redundant", "src/main/java/org/mockito/internal/handler/MockHandlerImpl.java", Severity.MEDIUM, null),
            new Annotation(27, "Variable 'delegatedObject' initializer 'null' is redundant", "src/main/java/org/mockito/internal/stubbing/defaultanswers/ForwardsInvocations.java", Severity.MEDIUM, null),
            new Annotation(60, "Condition 'invocations.isEmpty()' is always 'false'", "src/main/java/org/mockito/internal/junit/UnusedStubbings.java", Severity.MEDIUM, null),
            new Annotation(117, "Condition 'm1.getName() != null' is always 'true'", "src/main/java/org/mockito/internal/invocation/InvocationMatcher.java", Severity.MEDIUM, null),
            new Annotation(199, "'Optional.get()' without 'isPresent()' check", "subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java", Severity.MEDIUM, null)
        ]
    }
}
