name: create-release

on:
  pull_request:

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'release')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo 'hello world'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.pull_request.title }}
          generate_release_notes: true
          body_path: ${{ github.workspace }}-CHANGELOG.txt
