name: create-release

on:
  pull_request:

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'release')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo 'hello world'
