name: execute-test

on:
  pull_request:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: openjdk:8
    steps:
      - uses: actions/checkout@v2
      - run: sh mvnw clean test
